import React from 'react';

// headers.js
export const headersTable = (iconProps: React.ReactNode) => [
    { title: 'lớp', isVisible: true, icon: iconProps },
    { title: 'Nội dung bài kiểm tra', isVisible: true },
    { title: 'Môn học', icon: iconProps, isVisible: true },
    { title: 'Ngày làm bài', isVisible: true },
    { title: 'Thời lượng', isVisible: true },
    { title: 'Tình trạng', isVisible: true },
    { title: 'Bài làm', isVisible: true },
];
export const arrValueExam = [
    {
        class: '10A1',
        subject: 'Văn học',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 1,
    },
    {
        class: '10A2',
        subject: 'Toán hình học',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 2,
    },
    {
        class: '10A3',
        subject: 'Toán đại số',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 3,
    },
    {
        class: '11A10',
        subject: 'Văn học',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 2,
    },
    {
        class: '11A11',
        subject: 'Toán hình học',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 1,
    },
    {
        class: '11A12',
        subject: 'Anh văn',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 2,
    },
    {
        class: '12A1',
        subject: 'Văn học',
        exam_type: '1 tiết',
        exam_day: 'Thứ 5',
        dateStart: '21/08/2021',
        time: '12:00pm',
        duration: '45 phút',
        status: 3,
    },
];
